/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"

import axios from "axios"
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios"

export interface FileDto {
  id: string
}

export type RoleDtoId = { [key: string]: unknown }

export interface RoleDto {
  id: RoleDtoId
}

export type StatusDtoId = { [key: string]: unknown }

export interface StatusDto {
  id: StatusDtoId
}

export interface CreateUserDto {
  email: string
  password: string
  firstName: string
  lastName: string
  photo?: FileDto
  role?: RoleDto
  status?: StatusDto
}

export interface FileType {
  id: string
  path: string
}

export interface Role {
  id: number
  name: string
}

export interface Status {
  id: number
  name: string
}

export interface User {
  id: number
  email: string
  provider: string
  socialId: string
  firstName: string
  lastName: string
  photo: FileType
  role: Role
  status: Status
  createdAt: string
  updatedAt: string
  deletedAt: string
}

export interface InfinityPaginationUserResponseDto {
  data: User[]
  hasNextPage: boolean
}

export interface UpdateUserDto {
  email?: string
  password?: string
  firstName?: string
  lastName?: string
  photo?: FileDto
  role?: RoleDto
  status?: StatusDto
}

export interface FileResponseDto {
  file: FileType
}

export interface AuthEmailLoginDto {
  email: string
  password: string
}

export interface LoginResponseDto {
  token: string
  refreshToken: string
  tokenExpires: number
  user: User
}

export interface AuthRegisterLoginDto {
  email: string
  password: string
  firstName: string
  lastName: string
}

export interface AuthConfirmEmailDto {
  hash: string
}

export interface AuthForgotPasswordDto {
  email: string
}

export interface AuthResetPasswordDto {
  password: string
  hash: string
}

export interface RefreshResponseDto {
  token: string
  refreshToken: string
  tokenExpires: number
}

export interface AuthUpdateDto {
  photo?: FileDto
  firstName?: string
  lastName?: string
  email?: string
  password?: string
  oldPassword?: string
}

export interface AuthGoogleLoginDto {
  idToken: string
}

export type UsersControllerFindAllV1Params = {
  page?: number
  limit?: number
  filters?: string
  sort?: string
}

export type FilesLocalControllerUploadFileV1Body = {
  file?: Blob
}

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

export const usersControllerCreateV1 = (
  createUserDto: CreateUserDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<User>> => {
  return axios.post(`/api/v1/users`, createUserDto, options)
}

export const getUsersControllerCreateV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerCreateV1>>,
    TError,
    { data: CreateUserDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerCreateV1>>,
  TError,
  { data: CreateUserDto },
  TContext
> => {
  const mutationKey = ["usersControllerCreateV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerCreateV1>>,
    { data: CreateUserDto }
  > = (props) => {
    const { data } = props ?? {}

    return usersControllerCreateV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UsersControllerCreateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerCreateV1>>
>
export type UsersControllerCreateV1MutationBody = CreateUserDto
export type UsersControllerCreateV1MutationError = AxiosError<unknown>

export const useUsersControllerCreateV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersControllerCreateV1>>,
      TError,
      { data: CreateUserDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerCreateV1>>,
  TError,
  { data: CreateUserDto },
  TContext
> => {
  return useMutation(
    getUsersControllerCreateV1MutationOptions(options),
    queryClient
  )
}

export const usersControllerFindAllV1 = (
  params?: UsersControllerFindAllV1Params,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<InfinityPaginationUserResponseDto>> => {
  return axios.get(`/api/v1/users`, {
    ...options,
    params: { ...params, ...options?.params },
  })
}

export const getUsersControllerFindAllV1QueryKey = (
  params?: UsersControllerFindAllV1Params
) => {
  return [`/api/v1/users`, ...(params ? [params] : [])] as const
}

export const getUsersControllerFindAllV1QueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: UsersControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindAllV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getUsersControllerFindAllV1QueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof usersControllerFindAllV1>>
  > = ({ signal }) =>
    usersControllerFindAllV1(params, { signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerFindAllV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerFindAllV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerFindAllV1>>
>
export type UsersControllerFindAllV1QueryError = AxiosError<unknown>

export function useUsersControllerFindAllV1<
  TData = Awaited<ReturnType<typeof usersControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params: undefined | UsersControllerFindAllV1Params,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerFindAllV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useUsersControllerFindAllV1<
  TData = Awaited<ReturnType<typeof usersControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: UsersControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerFindAllV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useUsersControllerFindAllV1<
  TData = Awaited<ReturnType<typeof usersControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: UsersControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindAllV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useUsersControllerFindAllV1<
  TData = Awaited<ReturnType<typeof usersControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: UsersControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindAllV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getUsersControllerFindAllV1QueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

export const usersControllerFindOneV1 = (
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<User>> => {
  return axios.get(`/api/v1/users/${id}`, options)
}

export const getUsersControllerFindOneV1QueryKey = (id: string) => {
  return [`/api/v1/users/${id}`] as const
}

export const getUsersControllerFindOneV1QueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerFindOneV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindOneV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getUsersControllerFindOneV1QueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof usersControllerFindOneV1>>
  > = ({ signal }) => usersControllerFindOneV1(id, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerFindOneV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerFindOneV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerFindOneV1>>
>
export type UsersControllerFindOneV1QueryError = AxiosError<unknown>

export function useUsersControllerFindOneV1<
  TData = Awaited<ReturnType<typeof usersControllerFindOneV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindOneV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerFindOneV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerFindOneV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useUsersControllerFindOneV1<
  TData = Awaited<ReturnType<typeof usersControllerFindOneV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindOneV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerFindOneV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerFindOneV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useUsersControllerFindOneV1<
  TData = Awaited<ReturnType<typeof usersControllerFindOneV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindOneV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useUsersControllerFindOneV1<
  TData = Awaited<ReturnType<typeof usersControllerFindOneV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindOneV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getUsersControllerFindOneV1QueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

export const usersControllerUpdateV1 = (
  id: string,
  updateUserDto: UpdateUserDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<User>> => {
  return axios.patch(`/api/v1/users/${id}`, updateUserDto, options)
}

export const getUsersControllerUpdateV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateV1>>,
    TError,
    { id: string; data: UpdateUserDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUpdateV1>>,
  TError,
  { id: string; data: UpdateUserDto },
  TContext
> => {
  const mutationKey = ["usersControllerUpdateV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUpdateV1>>,
    { id: string; data: UpdateUserDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return usersControllerUpdateV1(id, data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UsersControllerUpdateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerUpdateV1>>
>
export type UsersControllerUpdateV1MutationBody = UpdateUserDto
export type UsersControllerUpdateV1MutationError = AxiosError<unknown>

export const useUsersControllerUpdateV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersControllerUpdateV1>>,
      TError,
      { id: string; data: UpdateUserDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUpdateV1>>,
  TError,
  { id: string; data: UpdateUserDto },
  TContext
> => {
  return useMutation(
    getUsersControllerUpdateV1MutationOptions(options),
    queryClient
  )
}

export const usersControllerRemoveV1 = (
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.delete(`/api/v1/users/${id}`, options)
}

export const getUsersControllerRemoveV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerRemoveV1>>,
    TError,
    { id: string },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerRemoveV1>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["usersControllerRemoveV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerRemoveV1>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return usersControllerRemoveV1(id, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UsersControllerRemoveV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerRemoveV1>>
>

export type UsersControllerRemoveV1MutationError = AxiosError<unknown>

export const useUsersControllerRemoveV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersControllerRemoveV1>>,
      TError,
      { id: string },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerRemoveV1>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getUsersControllerRemoveV1MutationOptions(options),
    queryClient
  )
}

export const filesLocalControllerUploadFileV1 = (
  filesLocalControllerUploadFileV1Body: FilesLocalControllerUploadFileV1Body,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<FileResponseDto>> => {
  const formData = new FormData()
  if (filesLocalControllerUploadFileV1Body.file !== undefined) {
    formData.append(`file`, filesLocalControllerUploadFileV1Body.file)
  }

  return axios.post(`/api/v1/files/upload`, formData, options)
}

export const getFilesLocalControllerUploadFileV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof filesLocalControllerUploadFileV1>>,
    TError,
    { data: FilesLocalControllerUploadFileV1Body },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof filesLocalControllerUploadFileV1>>,
  TError,
  { data: FilesLocalControllerUploadFileV1Body },
  TContext
> => {
  const mutationKey = ["filesLocalControllerUploadFileV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof filesLocalControllerUploadFileV1>>,
    { data: FilesLocalControllerUploadFileV1Body }
  > = (props) => {
    const { data } = props ?? {}

    return filesLocalControllerUploadFileV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type FilesLocalControllerUploadFileV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof filesLocalControllerUploadFileV1>>
>
export type FilesLocalControllerUploadFileV1MutationBody =
  FilesLocalControllerUploadFileV1Body
export type FilesLocalControllerUploadFileV1MutationError = AxiosError<unknown>

export const useFilesLocalControllerUploadFileV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof filesLocalControllerUploadFileV1>>,
      TError,
      { data: FilesLocalControllerUploadFileV1Body },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof filesLocalControllerUploadFileV1>>,
  TError,
  { data: FilesLocalControllerUploadFileV1Body },
  TContext
> => {
  return useMutation(
    getFilesLocalControllerUploadFileV1MutationOptions(options),
    queryClient
  )
}

export const authControllerLoginV1 = (
  authEmailLoginDto: AuthEmailLoginDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<LoginResponseDto>> => {
  return axios.post(`/api/v1/auth/email/login`, authEmailLoginDto, options)
}

export const getAuthControllerLoginV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLoginV1>>,
    TError,
    { data: AuthEmailLoginDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerLoginV1>>,
  TError,
  { data: AuthEmailLoginDto },
  TContext
> => {
  const mutationKey = ["authControllerLoginV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerLoginV1>>,
    { data: AuthEmailLoginDto }
  > = (props) => {
    const { data } = props ?? {}

    return authControllerLoginV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerLoginV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLoginV1>>
>
export type AuthControllerLoginV1MutationBody = AuthEmailLoginDto
export type AuthControllerLoginV1MutationError = AxiosError<unknown>

export const useAuthControllerLoginV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerLoginV1>>,
      TError,
      { data: AuthEmailLoginDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerLoginV1>>,
  TError,
  { data: AuthEmailLoginDto },
  TContext
> => {
  return useMutation(
    getAuthControllerLoginV1MutationOptions(options),
    queryClient
  )
}

export const authControllerRegisterV1 = (
  authRegisterLoginDto: AuthRegisterLoginDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post(
    `/api/v1/auth/email/register`,
    authRegisterLoginDto,
    options
  )
}

export const getAuthControllerRegisterV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRegisterV1>>,
    TError,
    { data: AuthRegisterLoginDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerRegisterV1>>,
  TError,
  { data: AuthRegisterLoginDto },
  TContext
> => {
  const mutationKey = ["authControllerRegisterV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerRegisterV1>>,
    { data: AuthRegisterLoginDto }
  > = (props) => {
    const { data } = props ?? {}

    return authControllerRegisterV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerRegisterV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRegisterV1>>
>
export type AuthControllerRegisterV1MutationBody = AuthRegisterLoginDto
export type AuthControllerRegisterV1MutationError = AxiosError<unknown>

export const useAuthControllerRegisterV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerRegisterV1>>,
      TError,
      { data: AuthRegisterLoginDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerRegisterV1>>,
  TError,
  { data: AuthRegisterLoginDto },
  TContext
> => {
  return useMutation(
    getAuthControllerRegisterV1MutationOptions(options),
    queryClient
  )
}

export const authControllerConfirmEmailV1 = (
  authConfirmEmailDto: AuthConfirmEmailDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post(`/api/v1/auth/email/confirm`, authConfirmEmailDto, options)
}

export const getAuthControllerConfirmEmailV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerConfirmEmailV1>>,
    TError,
    { data: AuthConfirmEmailDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerConfirmEmailV1>>,
  TError,
  { data: AuthConfirmEmailDto },
  TContext
> => {
  const mutationKey = ["authControllerConfirmEmailV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerConfirmEmailV1>>,
    { data: AuthConfirmEmailDto }
  > = (props) => {
    const { data } = props ?? {}

    return authControllerConfirmEmailV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerConfirmEmailV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerConfirmEmailV1>>
>
export type AuthControllerConfirmEmailV1MutationBody = AuthConfirmEmailDto
export type AuthControllerConfirmEmailV1MutationError = AxiosError<unknown>

export const useAuthControllerConfirmEmailV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerConfirmEmailV1>>,
      TError,
      { data: AuthConfirmEmailDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerConfirmEmailV1>>,
  TError,
  { data: AuthConfirmEmailDto },
  TContext
> => {
  return useMutation(
    getAuthControllerConfirmEmailV1MutationOptions(options),
    queryClient
  )
}

export const authControllerConfirmNewEmailV1 = (
  authConfirmEmailDto: AuthConfirmEmailDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post(
    `/api/v1/auth/email/confirm/new`,
    authConfirmEmailDto,
    options
  )
}

export const getAuthControllerConfirmNewEmailV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerConfirmNewEmailV1>>,
    TError,
    { data: AuthConfirmEmailDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerConfirmNewEmailV1>>,
  TError,
  { data: AuthConfirmEmailDto },
  TContext
> => {
  const mutationKey = ["authControllerConfirmNewEmailV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerConfirmNewEmailV1>>,
    { data: AuthConfirmEmailDto }
  > = (props) => {
    const { data } = props ?? {}

    return authControllerConfirmNewEmailV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerConfirmNewEmailV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerConfirmNewEmailV1>>
>
export type AuthControllerConfirmNewEmailV1MutationBody = AuthConfirmEmailDto
export type AuthControllerConfirmNewEmailV1MutationError = AxiosError<unknown>

export const useAuthControllerConfirmNewEmailV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerConfirmNewEmailV1>>,
      TError,
      { data: AuthConfirmEmailDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerConfirmNewEmailV1>>,
  TError,
  { data: AuthConfirmEmailDto },
  TContext
> => {
  return useMutation(
    getAuthControllerConfirmNewEmailV1MutationOptions(options),
    queryClient
  )
}

export const authControllerForgotPasswordV1 = (
  authForgotPasswordDto: AuthForgotPasswordDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post(
    `/api/v1/auth/forgot/password`,
    authForgotPasswordDto,
    options
  )
}

export const getAuthControllerForgotPasswordV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerForgotPasswordV1>>,
    TError,
    { data: AuthForgotPasswordDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerForgotPasswordV1>>,
  TError,
  { data: AuthForgotPasswordDto },
  TContext
> => {
  const mutationKey = ["authControllerForgotPasswordV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerForgotPasswordV1>>,
    { data: AuthForgotPasswordDto }
  > = (props) => {
    const { data } = props ?? {}

    return authControllerForgotPasswordV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerForgotPasswordV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerForgotPasswordV1>>
>
export type AuthControllerForgotPasswordV1MutationBody = AuthForgotPasswordDto
export type AuthControllerForgotPasswordV1MutationError = AxiosError<unknown>

export const useAuthControllerForgotPasswordV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerForgotPasswordV1>>,
      TError,
      { data: AuthForgotPasswordDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerForgotPasswordV1>>,
  TError,
  { data: AuthForgotPasswordDto },
  TContext
> => {
  return useMutation(
    getAuthControllerForgotPasswordV1MutationOptions(options),
    queryClient
  )
}

export const authControllerResetPasswordV1 = (
  authResetPasswordDto: AuthResetPasswordDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post(
    `/api/v1/auth/reset/password`,
    authResetPasswordDto,
    options
  )
}

export const getAuthControllerResetPasswordV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerResetPasswordV1>>,
    TError,
    { data: AuthResetPasswordDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerResetPasswordV1>>,
  TError,
  { data: AuthResetPasswordDto },
  TContext
> => {
  const mutationKey = ["authControllerResetPasswordV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerResetPasswordV1>>,
    { data: AuthResetPasswordDto }
  > = (props) => {
    const { data } = props ?? {}

    return authControllerResetPasswordV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerResetPasswordV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerResetPasswordV1>>
>
export type AuthControllerResetPasswordV1MutationBody = AuthResetPasswordDto
export type AuthControllerResetPasswordV1MutationError = AxiosError<unknown>

export const useAuthControllerResetPasswordV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerResetPasswordV1>>,
      TError,
      { data: AuthResetPasswordDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerResetPasswordV1>>,
  TError,
  { data: AuthResetPasswordDto },
  TContext
> => {
  return useMutation(
    getAuthControllerResetPasswordV1MutationOptions(options),
    queryClient
  )
}

export const authControllerMeV1 = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<User>> => {
  return axios.get(`/api/v1/auth/me`, options)
}

export const getAuthControllerMeV1QueryKey = () => {
  return [`/api/v1/auth/me`] as const
}

export const getAuthControllerMeV1QueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerMeV1>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof authControllerMeV1>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getAuthControllerMeV1QueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authControllerMeV1>>
  > = ({ signal }) => authControllerMeV1({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerMeV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerMeV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerMeV1>>
>
export type AuthControllerMeV1QueryError = AxiosError<unknown>

export function useAuthControllerMeV1<
  TData = Awaited<ReturnType<typeof authControllerMeV1>>,
  TError = AxiosError<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerMeV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerMeV1>>,
          TError,
          Awaited<ReturnType<typeof authControllerMeV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAuthControllerMeV1<
  TData = Awaited<ReturnType<typeof authControllerMeV1>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerMeV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerMeV1>>,
          TError,
          Awaited<ReturnType<typeof authControllerMeV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAuthControllerMeV1<
  TData = Awaited<ReturnType<typeof authControllerMeV1>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerMeV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useAuthControllerMeV1<
  TData = Awaited<ReturnType<typeof authControllerMeV1>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerMeV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getAuthControllerMeV1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

export const authControllerUpdateV1 = (
  authUpdateDto: AuthUpdateDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<User>> => {
  return axios.patch(`/api/v1/auth/me`, authUpdateDto, options)
}

export const getAuthControllerUpdateV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerUpdateV1>>,
    TError,
    { data: AuthUpdateDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerUpdateV1>>,
  TError,
  { data: AuthUpdateDto },
  TContext
> => {
  const mutationKey = ["authControllerUpdateV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerUpdateV1>>,
    { data: AuthUpdateDto }
  > = (props) => {
    const { data } = props ?? {}

    return authControllerUpdateV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerUpdateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerUpdateV1>>
>
export type AuthControllerUpdateV1MutationBody = AuthUpdateDto
export type AuthControllerUpdateV1MutationError = AxiosError<unknown>

export const useAuthControllerUpdateV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerUpdateV1>>,
      TError,
      { data: AuthUpdateDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerUpdateV1>>,
  TError,
  { data: AuthUpdateDto },
  TContext
> => {
  return useMutation(
    getAuthControllerUpdateV1MutationOptions(options),
    queryClient
  )
}

export const authControllerDeleteV1 = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.delete(`/api/v1/auth/me`, options)
}

export const getAuthControllerDeleteV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerDeleteV1>>,
    TError,
    void,
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerDeleteV1>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["authControllerDeleteV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerDeleteV1>>,
    void
  > = () => {
    return authControllerDeleteV1(axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerDeleteV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerDeleteV1>>
>

export type AuthControllerDeleteV1MutationError = AxiosError<unknown>

export const useAuthControllerDeleteV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerDeleteV1>>,
      TError,
      void,
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerDeleteV1>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getAuthControllerDeleteV1MutationOptions(options),
    queryClient
  )
}

export const authControllerRefreshV1 = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<RefreshResponseDto>> => {
  return axios.post(`/api/v1/auth/refresh`, undefined, options)
}

export const getAuthControllerRefreshV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRefreshV1>>,
    TError,
    void,
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerRefreshV1>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["authControllerRefreshV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerRefreshV1>>,
    void
  > = () => {
    return authControllerRefreshV1(axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerRefreshV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRefreshV1>>
>

export type AuthControllerRefreshV1MutationError = AxiosError<unknown>

export const useAuthControllerRefreshV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerRefreshV1>>,
      TError,
      void,
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerRefreshV1>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getAuthControllerRefreshV1MutationOptions(options),
    queryClient
  )
}

export const authControllerLogoutV1 = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post(`/api/v1/auth/logout`, undefined, options)
}

export const getAuthControllerLogoutV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogoutV1>>,
    TError,
    void,
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerLogoutV1>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["authControllerLogoutV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerLogoutV1>>,
    void
  > = () => {
    return authControllerLogoutV1(axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerLogoutV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLogoutV1>>
>

export type AuthControllerLogoutV1MutationError = AxiosError<unknown>

export const useAuthControllerLogoutV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerLogoutV1>>,
      TError,
      void,
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerLogoutV1>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getAuthControllerLogoutV1MutationOptions(options),
    queryClient
  )
}

export const authGoogleControllerLoginV1 = (
  authGoogleLoginDto: AuthGoogleLoginDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<LoginResponseDto>> => {
  return axios.post(`/api/v1/auth/google/login`, authGoogleLoginDto, options)
}

export const getAuthGoogleControllerLoginV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authGoogleControllerLoginV1>>,
    TError,
    { data: AuthGoogleLoginDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authGoogleControllerLoginV1>>,
  TError,
  { data: AuthGoogleLoginDto },
  TContext
> => {
  const mutationKey = ["authGoogleControllerLoginV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authGoogleControllerLoginV1>>,
    { data: AuthGoogleLoginDto }
  > = (props) => {
    const { data } = props ?? {}

    return authGoogleControllerLoginV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthGoogleControllerLoginV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authGoogleControllerLoginV1>>
>
export type AuthGoogleControllerLoginV1MutationBody = AuthGoogleLoginDto
export type AuthGoogleControllerLoginV1MutationError = AxiosError<unknown>

export const useAuthGoogleControllerLoginV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authGoogleControllerLoginV1>>,
      TError,
      { data: AuthGoogleLoginDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authGoogleControllerLoginV1>>,
  TError,
  { data: AuthGoogleLoginDto },
  TContext
> => {
  return useMutation(
    getAuthGoogleControllerLoginV1MutationOptions(options),
    queryClient
  )
}

export const homeControllerAppInfo = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get(`/`, options)
}

export const getHomeControllerAppInfoQueryKey = () => {
  return [`/`] as const
}

export const getHomeControllerAppInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof homeControllerAppInfo>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof homeControllerAppInfo>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getHomeControllerAppInfoQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof homeControllerAppInfo>>
  > = ({ signal }) => homeControllerAppInfo({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof homeControllerAppInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HomeControllerAppInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof homeControllerAppInfo>>
>
export type HomeControllerAppInfoQueryError = AxiosError<unknown>

export function useHomeControllerAppInfo<
  TData = Awaited<ReturnType<typeof homeControllerAppInfo>>,
  TError = AxiosError<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof homeControllerAppInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof homeControllerAppInfo>>,
          TError,
          Awaited<ReturnType<typeof homeControllerAppInfo>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useHomeControllerAppInfo<
  TData = Awaited<ReturnType<typeof homeControllerAppInfo>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof homeControllerAppInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof homeControllerAppInfo>>,
          TError,
          Awaited<ReturnType<typeof homeControllerAppInfo>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useHomeControllerAppInfo<
  TData = Awaited<ReturnType<typeof homeControllerAppInfo>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof homeControllerAppInfo>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useHomeControllerAppInfo<
  TData = Awaited<ReturnType<typeof homeControllerAppInfo>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof homeControllerAppInfo>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getHomeControllerAppInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}
