/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cyber Wolf API
 * 接口文档（成功响应经全局包装为 { code, msg, data }）
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"

import axios from "axios"
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios"

import type {
  CreateNewsCategoryDto,
  InfinityPaginationNewsCategoryResponseDto,
  NewsCategoriesAdminControllerFindAllV1Params,
  NewsCategory,
  UpdateNewsCategoryDto,
} from "./cyberWolfAPI.schemas"

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

/**
 * @summary 创建资讯分类
 */
export const newsCategoriesAdminControllerCreateV1 = (
  createNewsCategoryDto: CreateNewsCategoryDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<NewsCategory>> => {
  return axios.post(
    `/api/v1/admin/news-categories`,
    createNewsCategoryDto,
    options
  )
}

export const getNewsCategoriesAdminControllerCreateV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof newsCategoriesAdminControllerCreateV1>>,
    TError,
    { data: CreateNewsCategoryDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof newsCategoriesAdminControllerCreateV1>>,
  TError,
  { data: CreateNewsCategoryDto },
  TContext
> => {
  const mutationKey = ["newsCategoriesAdminControllerCreateV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof newsCategoriesAdminControllerCreateV1>>,
    { data: CreateNewsCategoryDto }
  > = (props) => {
    const { data } = props ?? {}

    return newsCategoriesAdminControllerCreateV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type NewsCategoriesAdminControllerCreateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof newsCategoriesAdminControllerCreateV1>>
>
export type NewsCategoriesAdminControllerCreateV1MutationBody =
  CreateNewsCategoryDto
export type NewsCategoriesAdminControllerCreateV1MutationError =
  AxiosError<unknown>

/**
 * @summary 创建资讯分类
 */
export const useNewsCategoriesAdminControllerCreateV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof newsCategoriesAdminControllerCreateV1>>,
      TError,
      { data: CreateNewsCategoryDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof newsCategoriesAdminControllerCreateV1>>,
  TError,
  { data: CreateNewsCategoryDto },
  TContext
> => {
  return useMutation(
    getNewsCategoriesAdminControllerCreateV1MutationOptions(options),
    queryClient
  )
}
/**
 * @summary 资讯分类列表（后台）
 */
export const newsCategoriesAdminControllerFindAllV1 = (
  params?: NewsCategoriesAdminControllerFindAllV1Params,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<InfinityPaginationNewsCategoryResponseDto>> => {
  return axios.get(`/api/v1/admin/news-categories`, {
    ...options,
    params: { ...params, ...options?.params },
  })
}

export const getNewsCategoriesAdminControllerFindAllV1QueryKey = (
  params?: NewsCategoriesAdminControllerFindAllV1Params
) => {
  return [`/api/v1/admin/news-categories`, ...(params ? [params] : [])] as const
}

export const getNewsCategoriesAdminControllerFindAllV1QueryOptions = <
  TData = Awaited<ReturnType<typeof newsCategoriesAdminControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: NewsCategoriesAdminControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsCategoriesAdminControllerFindAllV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getNewsCategoriesAdminControllerFindAllV1QueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof newsCategoriesAdminControllerFindAllV1>>
  > = ({ signal }) =>
    newsCategoriesAdminControllerFindAllV1(params, { signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof newsCategoriesAdminControllerFindAllV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NewsCategoriesAdminControllerFindAllV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof newsCategoriesAdminControllerFindAllV1>>
>
export type NewsCategoriesAdminControllerFindAllV1QueryError =
  AxiosError<unknown>

export function useNewsCategoriesAdminControllerFindAllV1<
  TData = Awaited<ReturnType<typeof newsCategoriesAdminControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params: undefined | NewsCategoriesAdminControllerFindAllV1Params,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsCategoriesAdminControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof newsCategoriesAdminControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof newsCategoriesAdminControllerFindAllV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNewsCategoriesAdminControllerFindAllV1<
  TData = Awaited<ReturnType<typeof newsCategoriesAdminControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: NewsCategoriesAdminControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsCategoriesAdminControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof newsCategoriesAdminControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof newsCategoriesAdminControllerFindAllV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNewsCategoriesAdminControllerFindAllV1<
  TData = Awaited<ReturnType<typeof newsCategoriesAdminControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: NewsCategoriesAdminControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsCategoriesAdminControllerFindAllV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary 资讯分类列表（后台）
 */

export function useNewsCategoriesAdminControllerFindAllV1<
  TData = Awaited<ReturnType<typeof newsCategoriesAdminControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: NewsCategoriesAdminControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsCategoriesAdminControllerFindAllV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getNewsCategoriesAdminControllerFindAllV1QueryOptions(
    params,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary 资讯分类详情
 */
export const newsCategoriesAdminControllerFindByIdV1 = (
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<NewsCategory | null>> => {
  return axios.get(`/api/v1/admin/news-categories/${id}`, options)
}

export const getNewsCategoriesAdminControllerFindByIdV1QueryKey = (
  id: string
) => {
  return [`/api/v1/admin/news-categories/${id}`] as const
}

export const getNewsCategoriesAdminControllerFindByIdV1QueryOptions = <
  TData = Awaited<ReturnType<typeof newsCategoriesAdminControllerFindByIdV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsCategoriesAdminControllerFindByIdV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getNewsCategoriesAdminControllerFindByIdV1QueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof newsCategoriesAdminControllerFindByIdV1>>
  > = ({ signal }) =>
    newsCategoriesAdminControllerFindByIdV1(id, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof newsCategoriesAdminControllerFindByIdV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NewsCategoriesAdminControllerFindByIdV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof newsCategoriesAdminControllerFindByIdV1>>
>
export type NewsCategoriesAdminControllerFindByIdV1QueryError =
  AxiosError<unknown>

export function useNewsCategoriesAdminControllerFindByIdV1<
  TData = Awaited<ReturnType<typeof newsCategoriesAdminControllerFindByIdV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsCategoriesAdminControllerFindByIdV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof newsCategoriesAdminControllerFindByIdV1>>,
          TError,
          Awaited<ReturnType<typeof newsCategoriesAdminControllerFindByIdV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNewsCategoriesAdminControllerFindByIdV1<
  TData = Awaited<ReturnType<typeof newsCategoriesAdminControllerFindByIdV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsCategoriesAdminControllerFindByIdV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof newsCategoriesAdminControllerFindByIdV1>>,
          TError,
          Awaited<ReturnType<typeof newsCategoriesAdminControllerFindByIdV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNewsCategoriesAdminControllerFindByIdV1<
  TData = Awaited<ReturnType<typeof newsCategoriesAdminControllerFindByIdV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsCategoriesAdminControllerFindByIdV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary 资讯分类详情
 */

export function useNewsCategoriesAdminControllerFindByIdV1<
  TData = Awaited<ReturnType<typeof newsCategoriesAdminControllerFindByIdV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsCategoriesAdminControllerFindByIdV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getNewsCategoriesAdminControllerFindByIdV1QueryOptions(
    id,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary 更新资讯分类
 */
export const newsCategoriesAdminControllerUpdateV1 = (
  id: string,
  updateNewsCategoryDto: UpdateNewsCategoryDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<NewsCategory | null>> => {
  return axios.patch(
    `/api/v1/admin/news-categories/${id}`,
    updateNewsCategoryDto,
    options
  )
}

export const getNewsCategoriesAdminControllerUpdateV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof newsCategoriesAdminControllerUpdateV1>>,
    TError,
    { id: string; data: UpdateNewsCategoryDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof newsCategoriesAdminControllerUpdateV1>>,
  TError,
  { id: string; data: UpdateNewsCategoryDto },
  TContext
> => {
  const mutationKey = ["newsCategoriesAdminControllerUpdateV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof newsCategoriesAdminControllerUpdateV1>>,
    { id: string; data: UpdateNewsCategoryDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return newsCategoriesAdminControllerUpdateV1(id, data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type NewsCategoriesAdminControllerUpdateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof newsCategoriesAdminControllerUpdateV1>>
>
export type NewsCategoriesAdminControllerUpdateV1MutationBody =
  UpdateNewsCategoryDto
export type NewsCategoriesAdminControllerUpdateV1MutationError =
  AxiosError<unknown>

/**
 * @summary 更新资讯分类
 */
export const useNewsCategoriesAdminControllerUpdateV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof newsCategoriesAdminControllerUpdateV1>>,
      TError,
      { id: string; data: UpdateNewsCategoryDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof newsCategoriesAdminControllerUpdateV1>>,
  TError,
  { id: string; data: UpdateNewsCategoryDto },
  TContext
> => {
  return useMutation(
    getNewsCategoriesAdminControllerUpdateV1MutationOptions(options),
    queryClient
  )
}
/**
 * @summary 删除资讯分类
 */
export const newsCategoriesAdminControllerRemoveV1 = (
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.delete(`/api/v1/admin/news-categories/${id}`, options)
}

export const getNewsCategoriesAdminControllerRemoveV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof newsCategoriesAdminControllerRemoveV1>>,
    TError,
    { id: string },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof newsCategoriesAdminControllerRemoveV1>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["newsCategoriesAdminControllerRemoveV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof newsCategoriesAdminControllerRemoveV1>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return newsCategoriesAdminControllerRemoveV1(id, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type NewsCategoriesAdminControllerRemoveV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof newsCategoriesAdminControllerRemoveV1>>
>

export type NewsCategoriesAdminControllerRemoveV1MutationError =
  AxiosError<unknown>

/**
 * @summary 删除资讯分类
 */
export const useNewsCategoriesAdminControllerRemoveV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof newsCategoriesAdminControllerRemoveV1>>,
      TError,
      { id: string },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof newsCategoriesAdminControllerRemoveV1>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getNewsCategoriesAdminControllerRemoveV1MutationOptions(options),
    queryClient
  )
}
/**
 * @summary 恢复资讯分类
 */
export const newsCategoriesAdminControllerRestoreV1 = (
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<NewsCategory>> => {
  return axios.patch(
    `/api/v1/admin/news-categories/${id}/restore`,
    undefined,
    options
  )
}

export const getNewsCategoriesAdminControllerRestoreV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof newsCategoriesAdminControllerRestoreV1>>,
    TError,
    { id: string },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof newsCategoriesAdminControllerRestoreV1>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["newsCategoriesAdminControllerRestoreV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof newsCategoriesAdminControllerRestoreV1>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return newsCategoriesAdminControllerRestoreV1(id, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type NewsCategoriesAdminControllerRestoreV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof newsCategoriesAdminControllerRestoreV1>>
>

export type NewsCategoriesAdminControllerRestoreV1MutationError =
  AxiosError<unknown>

/**
 * @summary 恢复资讯分类
 */
export const useNewsCategoriesAdminControllerRestoreV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof newsCategoriesAdminControllerRestoreV1>>,
      TError,
      { id: string },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof newsCategoriesAdminControllerRestoreV1>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getNewsCategoriesAdminControllerRestoreV1MutationOptions(options),
    queryClient
  )
}
