/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cyber Wolf API
 * 接口文档（成功响应经全局包装为 { code, msg, data }）
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"

import axios from "axios"
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios"

import type {
  ApiSuccessInfinityPaginationNewsArticleResponseDtoResponseDto,
  ApiSuccessNewsArticle201ResponseDto,
  ApiSuccessNewsArticleNullableResponseDto,
  ApiSuccessNewsArticleResponseDto,
  CreateNewsArticleDto,
  NewsArticlesAdminControllerFindAllV1Params,
  UpdateNewsArticleDto,
} from "./cyberWolfAPI.schemas"

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

/**
 * @summary 创建资讯
 */
export const newsArticlesAdminControllerCreateV1 = (
  createNewsArticleDto: CreateNewsArticleDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<ApiSuccessNewsArticle201ResponseDto>> => {
  return axios.post(`/api/v1/admin/news`, createNewsArticleDto, options)
}

export const getNewsArticlesAdminControllerCreateV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof newsArticlesAdminControllerCreateV1>>,
    TError,
    { data: CreateNewsArticleDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof newsArticlesAdminControllerCreateV1>>,
  TError,
  { data: CreateNewsArticleDto },
  TContext
> => {
  const mutationKey = ["newsArticlesAdminControllerCreateV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof newsArticlesAdminControllerCreateV1>>,
    { data: CreateNewsArticleDto }
  > = (props) => {
    const { data } = props ?? {}

    return newsArticlesAdminControllerCreateV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type NewsArticlesAdminControllerCreateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof newsArticlesAdminControllerCreateV1>>
>
export type NewsArticlesAdminControllerCreateV1MutationBody =
  CreateNewsArticleDto
export type NewsArticlesAdminControllerCreateV1MutationError =
  AxiosError<unknown>

/**
 * @summary 创建资讯
 */
export const useNewsArticlesAdminControllerCreateV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof newsArticlesAdminControllerCreateV1>>,
      TError,
      { data: CreateNewsArticleDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof newsArticlesAdminControllerCreateV1>>,
  TError,
  { data: CreateNewsArticleDto },
  TContext
> => {
  return useMutation(
    getNewsArticlesAdminControllerCreateV1MutationOptions(options),
    queryClient
  )
}
/**
 * @summary 资讯列表（后台）
 */
export const newsArticlesAdminControllerFindAllV1 = (
  params?: NewsArticlesAdminControllerFindAllV1Params,
  options?: AxiosRequestConfig
): Promise<
  AxiosResponse<ApiSuccessInfinityPaginationNewsArticleResponseDtoResponseDto>
> => {
  return axios.get(`/api/v1/admin/news`, {
    ...options,
    params: { ...params, ...options?.params },
  })
}

export const getNewsArticlesAdminControllerFindAllV1QueryKey = (
  params?: NewsArticlesAdminControllerFindAllV1Params
) => {
  return [`/api/v1/admin/news`, ...(params ? [params] : [])] as const
}

export const getNewsArticlesAdminControllerFindAllV1QueryOptions = <
  TData = Awaited<ReturnType<typeof newsArticlesAdminControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: NewsArticlesAdminControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesAdminControllerFindAllV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getNewsArticlesAdminControllerFindAllV1QueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof newsArticlesAdminControllerFindAllV1>>
  > = ({ signal }) =>
    newsArticlesAdminControllerFindAllV1(params, { signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof newsArticlesAdminControllerFindAllV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NewsArticlesAdminControllerFindAllV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof newsArticlesAdminControllerFindAllV1>>
>
export type NewsArticlesAdminControllerFindAllV1QueryError = AxiosError<unknown>

export function useNewsArticlesAdminControllerFindAllV1<
  TData = Awaited<ReturnType<typeof newsArticlesAdminControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params: undefined | NewsArticlesAdminControllerFindAllV1Params,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesAdminControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof newsArticlesAdminControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof newsArticlesAdminControllerFindAllV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNewsArticlesAdminControllerFindAllV1<
  TData = Awaited<ReturnType<typeof newsArticlesAdminControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: NewsArticlesAdminControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesAdminControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof newsArticlesAdminControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof newsArticlesAdminControllerFindAllV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNewsArticlesAdminControllerFindAllV1<
  TData = Awaited<ReturnType<typeof newsArticlesAdminControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: NewsArticlesAdminControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesAdminControllerFindAllV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary 资讯列表（后台）
 */

export function useNewsArticlesAdminControllerFindAllV1<
  TData = Awaited<ReturnType<typeof newsArticlesAdminControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: NewsArticlesAdminControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesAdminControllerFindAllV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getNewsArticlesAdminControllerFindAllV1QueryOptions(
    params,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary 资讯详情（后台）
 */
export const newsArticlesAdminControllerFindByIdV1 = (
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<ApiSuccessNewsArticleNullableResponseDto>> => {
  return axios.get(`/api/v1/admin/news/${id}`, options)
}

export const getNewsArticlesAdminControllerFindByIdV1QueryKey = (
  id: string
) => {
  return [`/api/v1/admin/news/${id}`] as const
}

export const getNewsArticlesAdminControllerFindByIdV1QueryOptions = <
  TData = Awaited<ReturnType<typeof newsArticlesAdminControllerFindByIdV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesAdminControllerFindByIdV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getNewsArticlesAdminControllerFindByIdV1QueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof newsArticlesAdminControllerFindByIdV1>>
  > = ({ signal }) =>
    newsArticlesAdminControllerFindByIdV1(id, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof newsArticlesAdminControllerFindByIdV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NewsArticlesAdminControllerFindByIdV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof newsArticlesAdminControllerFindByIdV1>>
>
export type NewsArticlesAdminControllerFindByIdV1QueryError =
  AxiosError<unknown>

export function useNewsArticlesAdminControllerFindByIdV1<
  TData = Awaited<ReturnType<typeof newsArticlesAdminControllerFindByIdV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesAdminControllerFindByIdV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof newsArticlesAdminControllerFindByIdV1>>,
          TError,
          Awaited<ReturnType<typeof newsArticlesAdminControllerFindByIdV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNewsArticlesAdminControllerFindByIdV1<
  TData = Awaited<ReturnType<typeof newsArticlesAdminControllerFindByIdV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesAdminControllerFindByIdV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof newsArticlesAdminControllerFindByIdV1>>,
          TError,
          Awaited<ReturnType<typeof newsArticlesAdminControllerFindByIdV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNewsArticlesAdminControllerFindByIdV1<
  TData = Awaited<ReturnType<typeof newsArticlesAdminControllerFindByIdV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesAdminControllerFindByIdV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary 资讯详情（后台）
 */

export function useNewsArticlesAdminControllerFindByIdV1<
  TData = Awaited<ReturnType<typeof newsArticlesAdminControllerFindByIdV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesAdminControllerFindByIdV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getNewsArticlesAdminControllerFindByIdV1QueryOptions(
    id,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary 更新资讯
 */
export const newsArticlesAdminControllerUpdateV1 = (
  id: string,
  updateNewsArticleDto: UpdateNewsArticleDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<ApiSuccessNewsArticleNullableResponseDto>> => {
  return axios.patch(`/api/v1/admin/news/${id}`, updateNewsArticleDto, options)
}

export const getNewsArticlesAdminControllerUpdateV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof newsArticlesAdminControllerUpdateV1>>,
    TError,
    { id: string; data: UpdateNewsArticleDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof newsArticlesAdminControllerUpdateV1>>,
  TError,
  { id: string; data: UpdateNewsArticleDto },
  TContext
> => {
  const mutationKey = ["newsArticlesAdminControllerUpdateV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof newsArticlesAdminControllerUpdateV1>>,
    { id: string; data: UpdateNewsArticleDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return newsArticlesAdminControllerUpdateV1(id, data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type NewsArticlesAdminControllerUpdateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof newsArticlesAdminControllerUpdateV1>>
>
export type NewsArticlesAdminControllerUpdateV1MutationBody =
  UpdateNewsArticleDto
export type NewsArticlesAdminControllerUpdateV1MutationError =
  AxiosError<unknown>

/**
 * @summary 更新资讯
 */
export const useNewsArticlesAdminControllerUpdateV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof newsArticlesAdminControllerUpdateV1>>,
      TError,
      { id: string; data: UpdateNewsArticleDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof newsArticlesAdminControllerUpdateV1>>,
  TError,
  { id: string; data: UpdateNewsArticleDto },
  TContext
> => {
  return useMutation(
    getNewsArticlesAdminControllerUpdateV1MutationOptions(options),
    queryClient
  )
}
/**
 * @summary 删除资讯
 */
export const newsArticlesAdminControllerRemoveV1 = (
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.delete(`/api/v1/admin/news/${id}`, options)
}

export const getNewsArticlesAdminControllerRemoveV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof newsArticlesAdminControllerRemoveV1>>,
    TError,
    { id: string },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof newsArticlesAdminControllerRemoveV1>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["newsArticlesAdminControllerRemoveV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof newsArticlesAdminControllerRemoveV1>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return newsArticlesAdminControllerRemoveV1(id, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type NewsArticlesAdminControllerRemoveV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof newsArticlesAdminControllerRemoveV1>>
>

export type NewsArticlesAdminControllerRemoveV1MutationError =
  AxiosError<unknown>

/**
 * @summary 删除资讯
 */
export const useNewsArticlesAdminControllerRemoveV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof newsArticlesAdminControllerRemoveV1>>,
      TError,
      { id: string },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof newsArticlesAdminControllerRemoveV1>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getNewsArticlesAdminControllerRemoveV1MutationOptions(options),
    queryClient
  )
}
/**
 * @summary 恢复资讯
 */
export const newsArticlesAdminControllerRestoreV1 = (
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<ApiSuccessNewsArticleResponseDto>> => {
  return axios.patch(`/api/v1/admin/news/${id}/restore`, undefined, options)
}

export const getNewsArticlesAdminControllerRestoreV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof newsArticlesAdminControllerRestoreV1>>,
    TError,
    { id: string },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof newsArticlesAdminControllerRestoreV1>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["newsArticlesAdminControllerRestoreV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof newsArticlesAdminControllerRestoreV1>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return newsArticlesAdminControllerRestoreV1(id, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type NewsArticlesAdminControllerRestoreV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof newsArticlesAdminControllerRestoreV1>>
>

export type NewsArticlesAdminControllerRestoreV1MutationError =
  AxiosError<unknown>

/**
 * @summary 恢复资讯
 */
export const useNewsArticlesAdminControllerRestoreV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof newsArticlesAdminControllerRestoreV1>>,
      TError,
      { id: string },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof newsArticlesAdminControllerRestoreV1>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getNewsArticlesAdminControllerRestoreV1MutationOptions(options),
    queryClient
  )
}
