/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
export interface NewsArticle {
  coverColor: string
  sourceName: string
  sourceId: string
  publishedAt: string
  coverImage: string
  category: string
  url: string
  summary: string
  title: string
  id: string
  createdAt: string
  updatedAt: string
}

export interface InfinityPaginationNewsArticleResponseDto {
  data: NewsArticle[]
  hasNextPage: boolean
}

export interface FileDto {
  id: string
}

export type RoleDtoId = { [key: string]: unknown }

export interface RoleDto {
  id: RoleDtoId
}

export type StatusDtoId = { [key: string]: unknown }

export interface StatusDto {
  id: StatusDtoId
}

export interface CreateUserDto {
  email: string
  password: string
  firstName: string
  lastName: string
  photo?: FileDto
  role?: RoleDto
  status?: StatusDto
}

export interface FileType {
  id: string
  path: string
}

export interface Role {
  id: number
  name: string
}

export interface Status {
  id: number
  name: string
}

export interface User {
  id: number
  email: string
  provider: string
  socialId: string
  firstName: string
  lastName: string
  photo: FileType
  role: Role
  status: Status
  createdAt: string
  updatedAt: string
  deletedAt: string
}

export interface InfinityPaginationUserResponseDto {
  data: User[]
  hasNextPage: boolean
}

export interface UpdateUserDto {
  email?: string
  password?: string
  firstName?: string
  lastName?: string
  photo?: FileDto
  role?: RoleDto
  status?: StatusDto
}

export interface FileResponseDto {
  file: FileType
}

export interface AuthEmailLoginDto {
  email: string
  password: string
}

export interface LoginResponseDto {
  token: string
  refreshToken: string
  tokenExpires: number
  user: User
}

export interface AuthRegisterLoginDto {
  email: string
  password: string
  firstName: string
  lastName: string
}

export interface AuthConfirmEmailDto {
  hash: string
}

export interface AuthForgotPasswordDto {
  email: string
}

export interface AuthResetPasswordDto {
  password: string
  hash: string
}

export interface RefreshResponseDto {
  token: string
  refreshToken: string
  tokenExpires: number
}

export interface AuthUpdateDto {
  photo?: FileDto
  firstName?: string
  lastName?: string
  email?: string
  password?: string
  oldPassword?: string
}

export interface AuthGoogleLoginDto {
  idToken: string
}

export type NewsArticlesControllerFindAllV1Params = {
  page?: number
  limit?: number
  /**
   * 按分类筛选（如 Market / Technology）
   */
  category?: string
}

export type UsersControllerFindAllV1Params = {
  page?: number
  limit?: number
  filters?: string
  sort?: string
}

export type FilesLocalControllerUploadFileV1Body = {
  file?: Blob
}
