/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"

import axios from "axios"
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios"

import type {
  AuthConfirmEmailDto,
  AuthEmailLoginDto,
  AuthForgotPasswordDto,
  AuthGoogleLoginDto,
  AuthRegisterLoginDto,
  AuthResetPasswordDto,
  AuthUpdateDto,
  LoginResponseDto,
  RefreshResponseDto,
  User,
} from "./api.schemas"

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

export const authControllerLoginV1 = (
  authEmailLoginDto: AuthEmailLoginDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<LoginResponseDto>> => {
  return axios.post(`/api/v1/auth/email/login`, authEmailLoginDto, options)
}

export const getAuthControllerLoginV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLoginV1>>,
    TError,
    { data: AuthEmailLoginDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerLoginV1>>,
  TError,
  { data: AuthEmailLoginDto },
  TContext
> => {
  const mutationKey = ["authControllerLoginV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerLoginV1>>,
    { data: AuthEmailLoginDto }
  > = (props) => {
    const { data } = props ?? {}

    return authControllerLoginV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerLoginV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLoginV1>>
>
export type AuthControllerLoginV1MutationBody = AuthEmailLoginDto
export type AuthControllerLoginV1MutationError = AxiosError<unknown>

export const useAuthControllerLoginV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerLoginV1>>,
      TError,
      { data: AuthEmailLoginDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerLoginV1>>,
  TError,
  { data: AuthEmailLoginDto },
  TContext
> => {
  return useMutation(
    getAuthControllerLoginV1MutationOptions(options),
    queryClient
  )
}
export const authControllerRegisterV1 = (
  authRegisterLoginDto: AuthRegisterLoginDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post(
    `/api/v1/auth/email/register`,
    authRegisterLoginDto,
    options
  )
}

export const getAuthControllerRegisterV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRegisterV1>>,
    TError,
    { data: AuthRegisterLoginDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerRegisterV1>>,
  TError,
  { data: AuthRegisterLoginDto },
  TContext
> => {
  const mutationKey = ["authControllerRegisterV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerRegisterV1>>,
    { data: AuthRegisterLoginDto }
  > = (props) => {
    const { data } = props ?? {}

    return authControllerRegisterV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerRegisterV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRegisterV1>>
>
export type AuthControllerRegisterV1MutationBody = AuthRegisterLoginDto
export type AuthControllerRegisterV1MutationError = AxiosError<unknown>

export const useAuthControllerRegisterV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerRegisterV1>>,
      TError,
      { data: AuthRegisterLoginDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerRegisterV1>>,
  TError,
  { data: AuthRegisterLoginDto },
  TContext
> => {
  return useMutation(
    getAuthControllerRegisterV1MutationOptions(options),
    queryClient
  )
}
export const authControllerConfirmEmailV1 = (
  authConfirmEmailDto: AuthConfirmEmailDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post(`/api/v1/auth/email/confirm`, authConfirmEmailDto, options)
}

export const getAuthControllerConfirmEmailV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerConfirmEmailV1>>,
    TError,
    { data: AuthConfirmEmailDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerConfirmEmailV1>>,
  TError,
  { data: AuthConfirmEmailDto },
  TContext
> => {
  const mutationKey = ["authControllerConfirmEmailV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerConfirmEmailV1>>,
    { data: AuthConfirmEmailDto }
  > = (props) => {
    const { data } = props ?? {}

    return authControllerConfirmEmailV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerConfirmEmailV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerConfirmEmailV1>>
>
export type AuthControllerConfirmEmailV1MutationBody = AuthConfirmEmailDto
export type AuthControllerConfirmEmailV1MutationError = AxiosError<unknown>

export const useAuthControllerConfirmEmailV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerConfirmEmailV1>>,
      TError,
      { data: AuthConfirmEmailDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerConfirmEmailV1>>,
  TError,
  { data: AuthConfirmEmailDto },
  TContext
> => {
  return useMutation(
    getAuthControllerConfirmEmailV1MutationOptions(options),
    queryClient
  )
}
export const authControllerConfirmNewEmailV1 = (
  authConfirmEmailDto: AuthConfirmEmailDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post(
    `/api/v1/auth/email/confirm/new`,
    authConfirmEmailDto,
    options
  )
}

export const getAuthControllerConfirmNewEmailV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerConfirmNewEmailV1>>,
    TError,
    { data: AuthConfirmEmailDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerConfirmNewEmailV1>>,
  TError,
  { data: AuthConfirmEmailDto },
  TContext
> => {
  const mutationKey = ["authControllerConfirmNewEmailV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerConfirmNewEmailV1>>,
    { data: AuthConfirmEmailDto }
  > = (props) => {
    const { data } = props ?? {}

    return authControllerConfirmNewEmailV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerConfirmNewEmailV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerConfirmNewEmailV1>>
>
export type AuthControllerConfirmNewEmailV1MutationBody = AuthConfirmEmailDto
export type AuthControllerConfirmNewEmailV1MutationError = AxiosError<unknown>

export const useAuthControllerConfirmNewEmailV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerConfirmNewEmailV1>>,
      TError,
      { data: AuthConfirmEmailDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerConfirmNewEmailV1>>,
  TError,
  { data: AuthConfirmEmailDto },
  TContext
> => {
  return useMutation(
    getAuthControllerConfirmNewEmailV1MutationOptions(options),
    queryClient
  )
}
export const authControllerForgotPasswordV1 = (
  authForgotPasswordDto: AuthForgotPasswordDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post(
    `/api/v1/auth/forgot/password`,
    authForgotPasswordDto,
    options
  )
}

export const getAuthControllerForgotPasswordV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerForgotPasswordV1>>,
    TError,
    { data: AuthForgotPasswordDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerForgotPasswordV1>>,
  TError,
  { data: AuthForgotPasswordDto },
  TContext
> => {
  const mutationKey = ["authControllerForgotPasswordV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerForgotPasswordV1>>,
    { data: AuthForgotPasswordDto }
  > = (props) => {
    const { data } = props ?? {}

    return authControllerForgotPasswordV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerForgotPasswordV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerForgotPasswordV1>>
>
export type AuthControllerForgotPasswordV1MutationBody = AuthForgotPasswordDto
export type AuthControllerForgotPasswordV1MutationError = AxiosError<unknown>

export const useAuthControllerForgotPasswordV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerForgotPasswordV1>>,
      TError,
      { data: AuthForgotPasswordDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerForgotPasswordV1>>,
  TError,
  { data: AuthForgotPasswordDto },
  TContext
> => {
  return useMutation(
    getAuthControllerForgotPasswordV1MutationOptions(options),
    queryClient
  )
}
export const authControllerResetPasswordV1 = (
  authResetPasswordDto: AuthResetPasswordDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post(
    `/api/v1/auth/reset/password`,
    authResetPasswordDto,
    options
  )
}

export const getAuthControllerResetPasswordV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerResetPasswordV1>>,
    TError,
    { data: AuthResetPasswordDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerResetPasswordV1>>,
  TError,
  { data: AuthResetPasswordDto },
  TContext
> => {
  const mutationKey = ["authControllerResetPasswordV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerResetPasswordV1>>,
    { data: AuthResetPasswordDto }
  > = (props) => {
    const { data } = props ?? {}

    return authControllerResetPasswordV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerResetPasswordV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerResetPasswordV1>>
>
export type AuthControllerResetPasswordV1MutationBody = AuthResetPasswordDto
export type AuthControllerResetPasswordV1MutationError = AxiosError<unknown>

export const useAuthControllerResetPasswordV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerResetPasswordV1>>,
      TError,
      { data: AuthResetPasswordDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerResetPasswordV1>>,
  TError,
  { data: AuthResetPasswordDto },
  TContext
> => {
  return useMutation(
    getAuthControllerResetPasswordV1MutationOptions(options),
    queryClient
  )
}
export const authControllerMeV1 = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<User>> => {
  return axios.get(`/api/v1/auth/me`, options)
}

export const getAuthControllerMeV1QueryKey = () => {
  return [`/api/v1/auth/me`] as const
}

export const getAuthControllerMeV1QueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerMeV1>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof authControllerMeV1>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getAuthControllerMeV1QueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authControllerMeV1>>
  > = ({ signal }) => authControllerMeV1({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerMeV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerMeV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerMeV1>>
>
export type AuthControllerMeV1QueryError = AxiosError<unknown>

export function useAuthControllerMeV1<
  TData = Awaited<ReturnType<typeof authControllerMeV1>>,
  TError = AxiosError<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerMeV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerMeV1>>,
          TError,
          Awaited<ReturnType<typeof authControllerMeV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAuthControllerMeV1<
  TData = Awaited<ReturnType<typeof authControllerMeV1>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerMeV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerMeV1>>,
          TError,
          Awaited<ReturnType<typeof authControllerMeV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAuthControllerMeV1<
  TData = Awaited<ReturnType<typeof authControllerMeV1>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerMeV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useAuthControllerMeV1<
  TData = Awaited<ReturnType<typeof authControllerMeV1>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerMeV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getAuthControllerMeV1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

export const authControllerUpdateV1 = (
  authUpdateDto: AuthUpdateDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<User>> => {
  return axios.patch(`/api/v1/auth/me`, authUpdateDto, options)
}

export const getAuthControllerUpdateV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerUpdateV1>>,
    TError,
    { data: AuthUpdateDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerUpdateV1>>,
  TError,
  { data: AuthUpdateDto },
  TContext
> => {
  const mutationKey = ["authControllerUpdateV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerUpdateV1>>,
    { data: AuthUpdateDto }
  > = (props) => {
    const { data } = props ?? {}

    return authControllerUpdateV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerUpdateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerUpdateV1>>
>
export type AuthControllerUpdateV1MutationBody = AuthUpdateDto
export type AuthControllerUpdateV1MutationError = AxiosError<unknown>

export const useAuthControllerUpdateV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerUpdateV1>>,
      TError,
      { data: AuthUpdateDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerUpdateV1>>,
  TError,
  { data: AuthUpdateDto },
  TContext
> => {
  return useMutation(
    getAuthControllerUpdateV1MutationOptions(options),
    queryClient
  )
}
export const authControllerDeleteV1 = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.delete(`/api/v1/auth/me`, options)
}

export const getAuthControllerDeleteV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerDeleteV1>>,
    TError,
    void,
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerDeleteV1>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["authControllerDeleteV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerDeleteV1>>,
    void
  > = () => {
    return authControllerDeleteV1(axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerDeleteV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerDeleteV1>>
>

export type AuthControllerDeleteV1MutationError = AxiosError<unknown>

export const useAuthControllerDeleteV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerDeleteV1>>,
      TError,
      void,
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerDeleteV1>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getAuthControllerDeleteV1MutationOptions(options),
    queryClient
  )
}
export const authControllerRefreshV1 = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<RefreshResponseDto>> => {
  return axios.post(`/api/v1/auth/refresh`, undefined, options)
}

export const getAuthControllerRefreshV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRefreshV1>>,
    TError,
    void,
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerRefreshV1>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["authControllerRefreshV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerRefreshV1>>,
    void
  > = () => {
    return authControllerRefreshV1(axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerRefreshV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRefreshV1>>
>

export type AuthControllerRefreshV1MutationError = AxiosError<unknown>

export const useAuthControllerRefreshV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerRefreshV1>>,
      TError,
      void,
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerRefreshV1>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getAuthControllerRefreshV1MutationOptions(options),
    queryClient
  )
}
export const authControllerLogoutV1 = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post(`/api/v1/auth/logout`, undefined, options)
}

export const getAuthControllerLogoutV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogoutV1>>,
    TError,
    void,
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerLogoutV1>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["authControllerLogoutV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerLogoutV1>>,
    void
  > = () => {
    return authControllerLogoutV1(axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthControllerLogoutV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLogoutV1>>
>

export type AuthControllerLogoutV1MutationError = AxiosError<unknown>

export const useAuthControllerLogoutV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerLogoutV1>>,
      TError,
      void,
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerLogoutV1>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getAuthControllerLogoutV1MutationOptions(options),
    queryClient
  )
}
export const authGoogleControllerLoginV1 = (
  authGoogleLoginDto: AuthGoogleLoginDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<LoginResponseDto>> => {
  return axios.post(`/api/v1/auth/google/login`, authGoogleLoginDto, options)
}

export const getAuthGoogleControllerLoginV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authGoogleControllerLoginV1>>,
    TError,
    { data: AuthGoogleLoginDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof authGoogleControllerLoginV1>>,
  TError,
  { data: AuthGoogleLoginDto },
  TContext
> => {
  const mutationKey = ["authGoogleControllerLoginV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authGoogleControllerLoginV1>>,
    { data: AuthGoogleLoginDto }
  > = (props) => {
    const { data } = props ?? {}

    return authGoogleControllerLoginV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthGoogleControllerLoginV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authGoogleControllerLoginV1>>
>
export type AuthGoogleControllerLoginV1MutationBody = AuthGoogleLoginDto
export type AuthGoogleControllerLoginV1MutationError = AxiosError<unknown>

export const useAuthGoogleControllerLoginV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authGoogleControllerLoginV1>>,
      TError,
      { data: AuthGoogleLoginDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authGoogleControllerLoginV1>>,
  TError,
  { data: AuthGoogleLoginDto },
  TContext
> => {
  return useMutation(
    getAuthGoogleControllerLoginV1MutationOptions(options),
    queryClient
  )
}
