/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cyber Wolf API
 * 接口文档（成功响应经全局包装为 { code, msg, data }）
 * OpenAPI spec version: 1.0
 */
export interface CreateNewsCategoryDto {
  name: string
  /** 越小越靠前 */
  sortOrder?: number
}

/**
 * @nullable
 */
export type NewsCategoryDeletedAt = { [key: string]: unknown } | null

export interface NewsCategory {
  name: string
  sortOrder: number
  id: string
  createdAt: string
  updatedAt: string
  /** @nullable */
  deletedAt?: NewsCategoryDeletedAt
}

export interface ApiSuccessNewsCategory201ResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 业务数据 */
  data: NewsCategory
}

export interface InfinityPaginationNewsCategoryResponseDto {
  /** 列表数据 */
  data: NewsCategory[]
  /** 是否有下一页 */
  hasNextPage: boolean
  /** 总条数 */
  total: number
}

export interface ApiSuccessInfinityPaginationNewsCategoryResponseDtoResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 分页数据（内层 data 为列表项数组） */
  data: InfinityPaginationNewsCategoryResponseDto
}

export interface ApiSuccessNewsCategoryNullableResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 业务数据 */
  data: NewsCategory | null
}

export interface UpdateNewsCategoryDto {
  name?: string
  /** 越小越靠前 */
  sortOrder?: number
}

export interface ApiSuccessNewsCategoryResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 业务数据 */
  data: NewsCategory
}

/**
 * @nullable
 */
export type NewsArticleDeletedAt = { [key: string]: unknown } | null

export interface NewsArticle {
  sourceName: string
  sourceId: string
  publishedAt: string
  /** @nullable */
  coverImage?: string | null
  category: string
  url: string
  summary: string
  title: string
  id: string
  createdAt: string
  updatedAt: string
  /** @nullable */
  deletedAt?: NewsArticleDeletedAt
}

export interface InfinityPaginationNewsArticleResponseDto {
  /** 列表数据 */
  data: NewsArticle[]
  /** 是否有下一页 */
  hasNextPage: boolean
  /** 总条数 */
  total: number
}

export interface ApiSuccessInfinityPaginationNewsArticleResponseDtoResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 分页数据（内层 data 为列表项数组） */
  data: InfinityPaginationNewsArticleResponseDto
}

export interface FetchResultDto {
  /** 来源名称 */
  source: string
  /** 新增条数 */
  added: number
  /** 跳过条数 */
  skipped: number
  /** 失败时的错误信息 */
  error?: string
}

export interface ApiSuccessFetchResultDtoArrayResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 业务数据列表 */
  data: FetchResultDto[]
}

export interface ApiSuccessNewsCategoryArrayResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 业务数据列表 */
  data: NewsCategory[]
}

export interface ApiSuccessNewsArticleNullableResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 业务数据 */
  data: NewsArticle | null
}

export interface CreateNewsArticleDto {
  sourceName: string
  sourceId: string
  publishedAt: string
  coverImage?: string
  category: string
  url: string
  summary: string
  title: string
}

export interface ApiSuccessNewsArticle201ResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 业务数据 */
  data: NewsArticle
}

export interface UpdateNewsArticleDto {
  sourceName?: string
  sourceId?: string
  publishedAt?: string
  coverImage?: string
  category?: string
  url?: string
  summary?: string
  title?: string
}

export interface ApiSuccessNewsArticleResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 业务数据 */
  data: NewsArticle
}

export interface Market {
  /** 交易对 */
  symbol: string
  /** 基础币种 */
  baseAsset: string
  /** 计价币种 */
  quoteAsset: string
  /** 最新价 */
  lastPrice: string
  /** 24h 涨跌幅（%） */
  priceChangePercent: string
  /** 24h 最高价 */
  highPrice: string
  /** 24h 最低价 */
  lowPrice: string
  /** 24h 成交量（基础币） */
  volume: string
  /** 24h 成交额（USDT） */
  quoteVolume: string
  /**
   * 币种图标 URL
   * @nullable
   */
  logoUrl: string | null
}

export interface InfinityPaginationMarketResponseDto {
  /** 列表数据 */
  data: Market[]
  /** 是否有下一页 */
  hasNextPage: boolean
  /** 总条数 */
  total: number
}

export interface ApiSuccessInfinityPaginationMarketResponseDtoResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 分页数据（内层 data 为列表项数组） */
  data: InfinityPaginationMarketResponseDto
}

export interface ApiSuccessMarketNullableResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 业务数据 */
  data: Market | null
}

export interface FileDto {
  id: string
}

export interface RoleDto {
  id: number
}

export interface StatusDto {
  id: number
}

export interface CreateUserDto {
  walletAddress?: string
  nickname?: string
  email: string
  password: string
  photo?: FileDto
  role?: RoleDto
  status?: StatusDto
}

export interface FileType {
  id: string
  path: string
}

export interface Role {
  id: number
  name: string
}

export interface Status {
  id: number
  name: string
}

export interface User {
  /** @nullable */
  walletAddress: string | null
  /** @nullable */
  nickname: string | null
  id: number
  email: string
  provider: string
  socialId: string
  photo: FileType
  role: Role
  status: Status
  createdAt: string
  updatedAt: string
  deletedAt: string
}

export interface ApiSuccessUser201ResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 业务数据 */
  data: User
}

export interface InfinityPaginationUserResponseDto {
  /** 列表数据 */
  data: User[]
  /** 是否有下一页 */
  hasNextPage: boolean
  /** 总条数 */
  total: number
}

export interface ApiSuccessInfinityPaginationUserResponseDtoResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 分页数据（内层 data 为列表项数组） */
  data: InfinityPaginationUserResponseDto
}

export interface ApiSuccessUserNullableResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 业务数据 */
  data: User | null
}

export interface UpdateUserDto {
  walletAddress?: string
  nickname?: string
  email?: string
  password?: string
  photo?: FileDto
  role?: RoleDto
  status?: StatusDto
}

export interface FileResponseDto {
  file: FileType
}

export interface ApiSuccessFileResponseDto201ResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 业务数据 */
  data: FileResponseDto
}

export interface AuthEmailLoginDto {
  email: string
  password: string
}

export interface LoginResponseDto {
  token: string
  refreshToken: string
  tokenExpires: number
  user: User
}

export interface ApiSuccessLoginResponseDtoResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 业务数据 */
  data: LoginResponseDto
}

export interface AuthRegisterLoginDto {
  email: string
  password: string
  nickname: string
}

export interface AuthConfirmEmailDto {
  hash: string
}

export interface AuthForgotPasswordDto {
  email: string
}

export interface AuthResetPasswordDto {
  password: string
  hash: string
}

export interface RefreshResponseDto {
  token: string
  refreshToken: string
  tokenExpires: number
}

export interface ApiSuccessRefreshResponseDtoResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 业务数据 */
  data: RefreshResponseDto
}

export interface AuthUpdateDto {
  photo?: FileDto
  nickname?: string
  email?: string
  password?: string
  oldPassword?: string
}

export interface AuthGoogleLoginDto {
  idToken: string
}

export interface AuthWalletNonceResponseDto {
  nonce: string
}

export interface ApiSuccessAuthWalletNonceResponseDtoResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 业务数据 */
  data: AuthWalletNonceResponseDto
}

export interface AuthWalletLoginDto {
  address: string
  /** EIP-4361 / SIWE message */
  message: string
  signature: string
  nonce: string
}

export interface AuthWalletBindEmailDto {
  email: string
  password?: string
}

export interface AppInfoDto {
  /** 应用名称 */
  name: string
}

export interface ApiSuccessAppInfoDtoResponseDto {
  /** 业务状态码 */
  code: number
  /** 提示信息 */
  msg: string
  /** 业务数据 */
  data: AppInfoDto
}

export type NewsCategoriesAdminControllerFindAllV1Params = {
  page?: number
  limit?: number
  /**
   * all=全部，notDeleted=未删除，deleted=已删除；默认 all
   */
  deletedStatus?: NewsCategoriesAdminControllerFindAllV1DeletedStatus
}

export type NewsCategoriesAdminControllerFindAllV1DeletedStatus =
  (typeof NewsCategoriesAdminControllerFindAllV1DeletedStatus)[keyof typeof NewsCategoriesAdminControllerFindAllV1DeletedStatus]

export const NewsCategoriesAdminControllerFindAllV1DeletedStatus = {
  all: "all",
  notDeleted: "notDeleted",
  deleted: "deleted",
} as const

export type NewsArticlesControllerFindAllV1Params = {
  page?: number
  limit?: number
  /**
   * 按分类筛选（如 Market / Technology）
   */
  category?: string
  /**
   * 按分类 id 筛选（存在时优先于 category 名字）
   */
  categoryId?: string
}

export type NewsArticlesAdminControllerFindAllV1Params = {
  page?: number
  limit?: number
  /**
   * 按分类筛选（如 Market / Technology）
   */
  category?: string
  /**
   * 按分类 id 筛选（存在时优先于 category 名字）
   */
  categoryId?: string
  /**
   * all=全部，notDeleted=未删除，deleted=已删除；默认 all
   */
  deletedStatus?: NewsArticlesAdminControllerFindAllV1DeletedStatus
}

export type NewsArticlesAdminControllerFindAllV1DeletedStatus =
  (typeof NewsArticlesAdminControllerFindAllV1DeletedStatus)[keyof typeof NewsArticlesAdminControllerFindAllV1DeletedStatus]

export const NewsArticlesAdminControllerFindAllV1DeletedStatus = {
  all: "all",
  notDeleted: "notDeleted",
  deleted: "deleted",
} as const

export type MarketsControllerFindAllV1Params = {
  /**
   * 页码
   */
  page?: number
  /**
   * 每页条数（最大 50）
   */
  limit?: number
  /**
   * 搜索关键词（匹配 symbol / baseAsset，如 BTC、BTCUSDT）
   */
  q?: string
}

export type UsersControllerFindAllV1Params = {
  page?: number
  limit?: number
  filters?: string
  sort?: string
}

export type FilesS3ControllerUploadFileV1Body = {
  file?: Blob
}
