/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query"
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query"

import axios from "axios"
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios"

import type {
  FileResponseDto,
  FilesS3ControllerUploadFileV1Body,
} from "./api.schemas"

export const filesS3ControllerUploadFileV1 = (
  filesS3ControllerUploadFileV1Body: FilesS3ControllerUploadFileV1Body,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<FileResponseDto>> => {
  const formData = new FormData()
  if (filesS3ControllerUploadFileV1Body.file !== undefined) {
    formData.append(`file`, filesS3ControllerUploadFileV1Body.file)
  }

  return axios.post(`/api/v1/files/upload`, formData, options)
}

export const getFilesS3ControllerUploadFileV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof filesS3ControllerUploadFileV1>>,
    TError,
    { data: FilesS3ControllerUploadFileV1Body },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof filesS3ControllerUploadFileV1>>,
  TError,
  { data: FilesS3ControllerUploadFileV1Body },
  TContext
> => {
  const mutationKey = ["filesS3ControllerUploadFileV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof filesS3ControllerUploadFileV1>>,
    { data: FilesS3ControllerUploadFileV1Body }
  > = (props) => {
    const { data } = props ?? {}

    return filesS3ControllerUploadFileV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type FilesS3ControllerUploadFileV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof filesS3ControllerUploadFileV1>>
>
export type FilesS3ControllerUploadFileV1MutationBody =
  FilesS3ControllerUploadFileV1Body
export type FilesS3ControllerUploadFileV1MutationError = AxiosError<unknown>

export const useFilesS3ControllerUploadFileV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof filesS3ControllerUploadFileV1>>,
      TError,
      { data: FilesS3ControllerUploadFileV1Body },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof filesS3ControllerUploadFileV1>>,
  TError,
  { data: FilesS3ControllerUploadFileV1Body },
  TContext
> => {
  return useMutation(
    getFilesS3ControllerUploadFileV1MutationOptions(options),
    queryClient
  )
}
