/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cyber Wolf API
 * 接口文档（成功响应经全局包装为 { code, msg, data }）
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query"
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query"

import axios from "axios"
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios"

import type {
  FileResponseDto,
  FilesLocalControllerUploadFileV1Body,
} from "./cyberWolfAPI.schemas"

/**
 * @summary 上传文件（本地）
 */
export const filesLocalControllerUploadFileV1 = (
  filesLocalControllerUploadFileV1Body: FilesLocalControllerUploadFileV1Body,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<FileResponseDto>> => {
  const formData = new FormData()
  if (filesLocalControllerUploadFileV1Body.file !== undefined) {
    formData.append(`file`, filesLocalControllerUploadFileV1Body.file)
  }

  return axios.post(`/api/v1/files/upload`, formData, options)
}

export const getFilesLocalControllerUploadFileV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof filesLocalControllerUploadFileV1>>,
    TError,
    { data: FilesLocalControllerUploadFileV1Body },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof filesLocalControllerUploadFileV1>>,
  TError,
  { data: FilesLocalControllerUploadFileV1Body },
  TContext
> => {
  const mutationKey = ["filesLocalControllerUploadFileV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof filesLocalControllerUploadFileV1>>,
    { data: FilesLocalControllerUploadFileV1Body }
  > = (props) => {
    const { data } = props ?? {}

    return filesLocalControllerUploadFileV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type FilesLocalControllerUploadFileV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof filesLocalControllerUploadFileV1>>
>
export type FilesLocalControllerUploadFileV1MutationBody =
  FilesLocalControllerUploadFileV1Body
export type FilesLocalControllerUploadFileV1MutationError = AxiosError<unknown>

/**
 * @summary 上传文件（本地）
 */
export const useFilesLocalControllerUploadFileV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof filesLocalControllerUploadFileV1>>,
      TError,
      { data: FilesLocalControllerUploadFileV1Body },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof filesLocalControllerUploadFileV1>>,
  TError,
  { data: FilesLocalControllerUploadFileV1Body },
  TContext
> => {
  return useMutation(
    getFilesLocalControllerUploadFileV1MutationOptions(options),
    queryClient
  )
}
