/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cyber Wolf API
 * 接口文档（成功响应经全局包装为 { code, msg, data }）
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query"
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"

import axios from "axios"
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios"

import type {
  InfinityPaginationMarketResponseDto,
  Market,
  MarketsControllerFindAllV1Params,
} from "./cyberWolfAPI.schemas"

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

/**
 * @summary USDT 行情列表
 */
export const marketsControllerFindAllV1 = (
  params?: MarketsControllerFindAllV1Params,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<InfinityPaginationMarketResponseDto>> => {
  return axios.get(`/api/v1/markets`, {
    ...options,
    params: { ...params, ...options?.params },
  })
}

export const getMarketsControllerFindAllV1QueryKey = (
  params?: MarketsControllerFindAllV1Params
) => {
  return [`/api/v1/markets`, ...(params ? [params] : [])] as const
}

export const getMarketsControllerFindAllV1QueryOptions = <
  TData = Awaited<ReturnType<typeof marketsControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: MarketsControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof marketsControllerFindAllV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getMarketsControllerFindAllV1QueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof marketsControllerFindAllV1>>
  > = ({ signal }) =>
    marketsControllerFindAllV1(params, { signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof marketsControllerFindAllV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MarketsControllerFindAllV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof marketsControllerFindAllV1>>
>
export type MarketsControllerFindAllV1QueryError = AxiosError<unknown>

export function useMarketsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof marketsControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params: undefined | MarketsControllerFindAllV1Params,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof marketsControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof marketsControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof marketsControllerFindAllV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useMarketsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof marketsControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: MarketsControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof marketsControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof marketsControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof marketsControllerFindAllV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useMarketsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof marketsControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: MarketsControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof marketsControllerFindAllV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary USDT 行情列表
 */

export function useMarketsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof marketsControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: MarketsControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof marketsControllerFindAllV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getMarketsControllerFindAllV1QueryOptions(
    params,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary 单币行情详情
 */
export const marketsControllerFindOneV1 = (
  symbol: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<Market | null>> => {
  return axios.get(`/api/v1/markets/${symbol}`, options)
}

export const getMarketsControllerFindOneV1QueryKey = (symbol: string) => {
  return [`/api/v1/markets/${symbol}`] as const
}

export const getMarketsControllerFindOneV1QueryOptions = <
  TData = Awaited<ReturnType<typeof marketsControllerFindOneV1>>,
  TError = AxiosError<unknown>,
>(
  symbol: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof marketsControllerFindOneV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getMarketsControllerFindOneV1QueryKey(symbol)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof marketsControllerFindOneV1>>
  > = ({ signal }) =>
    marketsControllerFindOneV1(symbol, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: symbol !== null && symbol !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof marketsControllerFindOneV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MarketsControllerFindOneV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof marketsControllerFindOneV1>>
>
export type MarketsControllerFindOneV1QueryError = AxiosError<unknown>

export function useMarketsControllerFindOneV1<
  TData = Awaited<ReturnType<typeof marketsControllerFindOneV1>>,
  TError = AxiosError<unknown>,
>(
  symbol: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof marketsControllerFindOneV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof marketsControllerFindOneV1>>,
          TError,
          Awaited<ReturnType<typeof marketsControllerFindOneV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useMarketsControllerFindOneV1<
  TData = Awaited<ReturnType<typeof marketsControllerFindOneV1>>,
  TError = AxiosError<unknown>,
>(
  symbol: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof marketsControllerFindOneV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof marketsControllerFindOneV1>>,
          TError,
          Awaited<ReturnType<typeof marketsControllerFindOneV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useMarketsControllerFindOneV1<
  TData = Awaited<ReturnType<typeof marketsControllerFindOneV1>>,
  TError = AxiosError<unknown>,
>(
  symbol: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof marketsControllerFindOneV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary 单币行情详情
 */

export function useMarketsControllerFindOneV1<
  TData = Awaited<ReturnType<typeof marketsControllerFindOneV1>>,
  TError = AxiosError<unknown>,
>(
  symbol: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof marketsControllerFindOneV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getMarketsControllerFindOneV1QueryOptions(
    symbol,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}
