/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"

import axios from "axios"
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios"

import type {
  InfinityPaginationNewsArticleResponseDto,
  NewsArticle,
  NewsArticlesControllerFindAllV1Params,
} from "./api.schemas"

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

export const newsArticlesControllerFindAllV1 = (
  params?: NewsArticlesControllerFindAllV1Params,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<InfinityPaginationNewsArticleResponseDto>> => {
  return axios.get(`/api/v1/news`, {
    ...options,
    params: { ...params, ...options?.params },
  })
}

export const getNewsArticlesControllerFindAllV1QueryKey = (
  params?: NewsArticlesControllerFindAllV1Params
) => {
  return [`/api/v1/news`, ...(params ? [params] : [])] as const
}

export const getNewsArticlesControllerFindAllV1QueryOptions = <
  TData = Awaited<ReturnType<typeof newsArticlesControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: NewsArticlesControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesControllerFindAllV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getNewsArticlesControllerFindAllV1QueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof newsArticlesControllerFindAllV1>>
  > = ({ signal }) =>
    newsArticlesControllerFindAllV1(params, { signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof newsArticlesControllerFindAllV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NewsArticlesControllerFindAllV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof newsArticlesControllerFindAllV1>>
>
export type NewsArticlesControllerFindAllV1QueryError = AxiosError<unknown>

export function useNewsArticlesControllerFindAllV1<
  TData = Awaited<ReturnType<typeof newsArticlesControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params: undefined | NewsArticlesControllerFindAllV1Params,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof newsArticlesControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof newsArticlesControllerFindAllV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNewsArticlesControllerFindAllV1<
  TData = Awaited<ReturnType<typeof newsArticlesControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: NewsArticlesControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof newsArticlesControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof newsArticlesControllerFindAllV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNewsArticlesControllerFindAllV1<
  TData = Awaited<ReturnType<typeof newsArticlesControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: NewsArticlesControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesControllerFindAllV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useNewsArticlesControllerFindAllV1<
  TData = Awaited<ReturnType<typeof newsArticlesControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: NewsArticlesControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesControllerFindAllV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getNewsArticlesControllerFindAllV1QueryOptions(
    params,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

export const newsArticlesControllerFetchV1 = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.post(`/api/v1/news/fetch`, undefined, options)
}

export const getNewsArticlesControllerFetchV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof newsArticlesControllerFetchV1>>,
    TError,
    void,
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof newsArticlesControllerFetchV1>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["newsArticlesControllerFetchV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof newsArticlesControllerFetchV1>>,
    void
  > = () => {
    return newsArticlesControllerFetchV1(axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type NewsArticlesControllerFetchV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof newsArticlesControllerFetchV1>>
>

export type NewsArticlesControllerFetchV1MutationError = AxiosError<unknown>

export const useNewsArticlesControllerFetchV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof newsArticlesControllerFetchV1>>,
      TError,
      void,
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof newsArticlesControllerFetchV1>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getNewsArticlesControllerFetchV1MutationOptions(options),
    queryClient
  )
}
export const newsArticlesControllerFindCategoriesV1 = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<string[]>> => {
  return axios.get(`/api/v1/news/categories`, options)
}

export const getNewsArticlesControllerFindCategoriesV1QueryKey = () => {
  return [`/api/v1/news/categories`] as const
}

export const getNewsArticlesControllerFindCategoriesV1QueryOptions = <
  TData = Awaited<ReturnType<typeof newsArticlesControllerFindCategoriesV1>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof newsArticlesControllerFindCategoriesV1>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getNewsArticlesControllerFindCategoriesV1QueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof newsArticlesControllerFindCategoriesV1>>
  > = ({ signal }) =>
    newsArticlesControllerFindCategoriesV1({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof newsArticlesControllerFindCategoriesV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NewsArticlesControllerFindCategoriesV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof newsArticlesControllerFindCategoriesV1>>
>
export type NewsArticlesControllerFindCategoriesV1QueryError =
  AxiosError<unknown>

export function useNewsArticlesControllerFindCategoriesV1<
  TData = Awaited<ReturnType<typeof newsArticlesControllerFindCategoriesV1>>,
  TError = AxiosError<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesControllerFindCategoriesV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof newsArticlesControllerFindCategoriesV1>>,
          TError,
          Awaited<ReturnType<typeof newsArticlesControllerFindCategoriesV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNewsArticlesControllerFindCategoriesV1<
  TData = Awaited<ReturnType<typeof newsArticlesControllerFindCategoriesV1>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesControllerFindCategoriesV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof newsArticlesControllerFindCategoriesV1>>,
          TError,
          Awaited<ReturnType<typeof newsArticlesControllerFindCategoriesV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNewsArticlesControllerFindCategoriesV1<
  TData = Awaited<ReturnType<typeof newsArticlesControllerFindCategoriesV1>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesControllerFindCategoriesV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useNewsArticlesControllerFindCategoriesV1<
  TData = Awaited<ReturnType<typeof newsArticlesControllerFindCategoriesV1>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesControllerFindCategoriesV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions =
    getNewsArticlesControllerFindCategoriesV1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

export const newsArticlesControllerFindByIdV1 = (
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<NewsArticle>> => {
  return axios.get(`/api/v1/news/${id}`, options)
}

export const getNewsArticlesControllerFindByIdV1QueryKey = (id: string) => {
  return [`/api/v1/news/${id}`] as const
}

export const getNewsArticlesControllerFindByIdV1QueryOptions = <
  TData = Awaited<ReturnType<typeof newsArticlesControllerFindByIdV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesControllerFindByIdV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getNewsArticlesControllerFindByIdV1QueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof newsArticlesControllerFindByIdV1>>
  > = ({ signal }) =>
    newsArticlesControllerFindByIdV1(id, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof newsArticlesControllerFindByIdV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NewsArticlesControllerFindByIdV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof newsArticlesControllerFindByIdV1>>
>
export type NewsArticlesControllerFindByIdV1QueryError = AxiosError<unknown>

export function useNewsArticlesControllerFindByIdV1<
  TData = Awaited<ReturnType<typeof newsArticlesControllerFindByIdV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesControllerFindByIdV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof newsArticlesControllerFindByIdV1>>,
          TError,
          Awaited<ReturnType<typeof newsArticlesControllerFindByIdV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNewsArticlesControllerFindByIdV1<
  TData = Awaited<ReturnType<typeof newsArticlesControllerFindByIdV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesControllerFindByIdV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof newsArticlesControllerFindByIdV1>>,
          TError,
          Awaited<ReturnType<typeof newsArticlesControllerFindByIdV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNewsArticlesControllerFindByIdV1<
  TData = Awaited<ReturnType<typeof newsArticlesControllerFindByIdV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesControllerFindByIdV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useNewsArticlesControllerFindByIdV1<
  TData = Awaited<ReturnType<typeof newsArticlesControllerFindByIdV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof newsArticlesControllerFindByIdV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getNewsArticlesControllerFindByIdV1QueryOptions(
    id,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}
