/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cyber Wolf API
 * 接口文档（成功响应经全局包装为 { code, msg, data }）
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"

import axios from "axios"
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios"

import type {
  CreateUserDto,
  InfinityPaginationUserResponseDto,
  UpdateUserDto,
  User,
  UsersControllerFindAllV1Params,
} from "./cyberWolfAPI.schemas"

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

/**
 * @summary 创建用户
 */
export const usersControllerCreateV1 = (
  createUserDto: CreateUserDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<User>> => {
  return axios.post(`/api/v1/users`, createUserDto, options)
}

export const getUsersControllerCreateV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerCreateV1>>,
    TError,
    { data: CreateUserDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerCreateV1>>,
  TError,
  { data: CreateUserDto },
  TContext
> => {
  const mutationKey = ["usersControllerCreateV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerCreateV1>>,
    { data: CreateUserDto }
  > = (props) => {
    const { data } = props ?? {}

    return usersControllerCreateV1(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UsersControllerCreateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerCreateV1>>
>
export type UsersControllerCreateV1MutationBody = CreateUserDto
export type UsersControllerCreateV1MutationError = AxiosError<unknown>

/**
 * @summary 创建用户
 */
export const useUsersControllerCreateV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersControllerCreateV1>>,
      TError,
      { data: CreateUserDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerCreateV1>>,
  TError,
  { data: CreateUserDto },
  TContext
> => {
  return useMutation(
    getUsersControllerCreateV1MutationOptions(options),
    queryClient
  )
}
/**
 * @summary 用户列表
 */
export const usersControllerFindAllV1 = (
  params?: UsersControllerFindAllV1Params,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<InfinityPaginationUserResponseDto>> => {
  return axios.get(`/api/v1/users`, {
    ...options,
    params: { ...params, ...options?.params },
  })
}

export const getUsersControllerFindAllV1QueryKey = (
  params?: UsersControllerFindAllV1Params
) => {
  return [`/api/v1/users`, ...(params ? [params] : [])] as const
}

export const getUsersControllerFindAllV1QueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: UsersControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindAllV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getUsersControllerFindAllV1QueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof usersControllerFindAllV1>>
  > = ({ signal }) =>
    usersControllerFindAllV1(params, { signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerFindAllV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerFindAllV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerFindAllV1>>
>
export type UsersControllerFindAllV1QueryError = AxiosError<unknown>

export function useUsersControllerFindAllV1<
  TData = Awaited<ReturnType<typeof usersControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params: undefined | UsersControllerFindAllV1Params,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerFindAllV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useUsersControllerFindAllV1<
  TData = Awaited<ReturnType<typeof usersControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: UsersControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerFindAllV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useUsersControllerFindAllV1<
  TData = Awaited<ReturnType<typeof usersControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: UsersControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindAllV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary 用户列表
 */

export function useUsersControllerFindAllV1<
  TData = Awaited<ReturnType<typeof usersControllerFindAllV1>>,
  TError = AxiosError<unknown>,
>(
  params?: UsersControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindAllV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getUsersControllerFindAllV1QueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary 用户详情
 */
export const usersControllerFindOneV1 = (
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<User | null>> => {
  return axios.get(`/api/v1/users/${id}`, options)
}

export const getUsersControllerFindOneV1QueryKey = (id: string) => {
  return [`/api/v1/users/${id}`] as const
}

export const getUsersControllerFindOneV1QueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerFindOneV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindOneV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getUsersControllerFindOneV1QueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof usersControllerFindOneV1>>
  > = ({ signal }) => usersControllerFindOneV1(id, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerFindOneV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerFindOneV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerFindOneV1>>
>
export type UsersControllerFindOneV1QueryError = AxiosError<unknown>

export function useUsersControllerFindOneV1<
  TData = Awaited<ReturnType<typeof usersControllerFindOneV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindOneV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerFindOneV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerFindOneV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useUsersControllerFindOneV1<
  TData = Awaited<ReturnType<typeof usersControllerFindOneV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindOneV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerFindOneV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerFindOneV1>>
        >,
        "initialData"
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useUsersControllerFindOneV1<
  TData = Awaited<ReturnType<typeof usersControllerFindOneV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindOneV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary 用户详情
 */

export function useUsersControllerFindOneV1<
  TData = Awaited<ReturnType<typeof usersControllerFindOneV1>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerFindOneV1>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getUsersControllerFindOneV1QueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary 更新用户
 */
export const usersControllerUpdateV1 = (
  id: string,
  updateUserDto: UpdateUserDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<User | null>> => {
  return axios.patch(`/api/v1/users/${id}`, updateUserDto, options)
}

export const getUsersControllerUpdateV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateV1>>,
    TError,
    { id: string; data: UpdateUserDto },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUpdateV1>>,
  TError,
  { id: string; data: UpdateUserDto },
  TContext
> => {
  const mutationKey = ["usersControllerUpdateV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUpdateV1>>,
    { id: string; data: UpdateUserDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return usersControllerUpdateV1(id, data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UsersControllerUpdateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerUpdateV1>>
>
export type UsersControllerUpdateV1MutationBody = UpdateUserDto
export type UsersControllerUpdateV1MutationError = AxiosError<unknown>

/**
 * @summary 更新用户
 */
export const useUsersControllerUpdateV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersControllerUpdateV1>>,
      TError,
      { id: string; data: UpdateUserDto },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUpdateV1>>,
  TError,
  { id: string; data: UpdateUserDto },
  TContext
> => {
  return useMutation(
    getUsersControllerUpdateV1MutationOptions(options),
    queryClient
  )
}
/**
 * @summary 删除用户
 */
export const usersControllerRemoveV1 = (
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.delete(`/api/v1/users/${id}`, options)
}

export const getUsersControllerRemoveV1MutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerRemoveV1>>,
    TError,
    { id: string },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerRemoveV1>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["usersControllerRemoveV1"]
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerRemoveV1>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return usersControllerRemoveV1(id, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UsersControllerRemoveV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerRemoveV1>>
>

export type UsersControllerRemoveV1MutationError = AxiosError<unknown>

/**
 * @summary 删除用户
 */
export const useUsersControllerRemoveV1 = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersControllerRemoveV1>>,
      TError,
      { id: string },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerRemoveV1>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getUsersControllerRemoveV1MutationOptions(options),
    queryClient
  )
}
